spring.datasource.url=jdbc:mysql://yamabiko.proxy.rlwy.net:35225/railway
spring.datasource.username=root
spring.datasource.password=SyUvwIQzPMMHgztLPMVWBocGqogtgrhX
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
